apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: asteroidmining-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000  # Adjust according to your FastAPI application port
          env:
            - name: DB_SERVER
              value: {{ .Release.Name }}-mongodb
            - name: DB_USER
              value: {{ .Values.mongodb.auth.username }}
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb
                  key: mongodb-root-password
            - name: DB_NAME
              value: {{ .Values.mongodb.auth.database }}
